"""Compile source-grounded video plans into deterministic Manim scenes."""

import importlib.util
import json
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from .io import write_json
from .models import ContentPlan, ManimPrimitiveSpec, ManimSceneSpec, NarrationCue, NarrationTrack


SAFE_ZONE = {"top": 170, "right": 90, "bottom": 310, "left": 90}
CAPTION_RAIL = {"top": 1440, "bottom": 1600, "left": 90, "right": 990}


def _caption_payload(cue: Optional[NarrationCue], fallback: str, duration: float) -> List[Dict[str, object]]:
    if cue is None or not cue.words:
        return [{"text": fallback, "start_seconds": 0.0, "end_seconds": duration}]
    chunks: List[Dict[str, object]] = []
    current = []
    for word in cue.words:
        current.append(word)
        chunk_duration = current[-1].end_seconds - current[0].start_seconds
        if len(current) >= 4 or chunk_duration >= 1.9 or word.text.endswith((".", "!", "?")):
            chunks.append(
                {
                    "text": " ".join(item.text for item in current),
                    "start_seconds": round(current[0].start_seconds - cue.start_seconds, 4),
                    "end_seconds": round(current[-1].end_seconds - cue.start_seconds, 4),
                }
            )
            current = []
    if current:
        chunks.append(
            {
                "text": " ".join(item.text for item in current),
                "start_seconds": round(current[0].start_seconds - cue.start_seconds, 4),
                "end_seconds": round(current[-1].end_seconds - cue.start_seconds, 4),
            }
        )
    return chunks


def compile_manim_scene(plan: ContentPlan, narration: Optional[NarrationTrack] = None) -> ManimSceneSpec:
    if plan.format != "video":
        raise ValueError("only video plans compile to ManimSceneSpec")
    elapsed = 0.0
    primitives: List[ManimPrimitiveSpec] = []
    cue_by_id = {cue.beat_id: cue for cue in narration.cues} if narration else {}
    for beat_index, beat in enumerate(plan.beats):
        cue = cue_by_id.get(beat.id)
        primitives.append(
            ManimPrimitiveSpec(
                kind=beat.primitive,
                title=beat.headline,
                body=beat.on_screen_text,
                claim_ids=beat.claim_ids,
                source_label=beat.source_label,
                start_seconds=elapsed,
                duration_seconds=beat.duration_seconds,
                params={
                    "purpose": beat.purpose,
                    "beat_index": beat_index,
                    "beat_count": len(plan.beats),
                    "captions": _caption_payload(cue, beat.narration, beat.duration_seconds),
                },
            )
        )
        elapsed += beat.duration_seconds
    return ManimSceneSpec(
        id="manim_" + plan.id,
        width=1080,
        height=1920,
        fps=30,
        background="#07111F",
        safe_zone=SAFE_ZONE.copy(),
        caption_rail=CAPTION_RAIL.copy(),
        primitives=primitives,
        duration_seconds=elapsed,
    )


def write_manim_spec(job_dir: Path, spec: ManimSceneSpec) -> Path:
    path = job_dir / "video" / "manim" / "spec.json"
    write_json(path, spec)
    return path


def _legacy_scene_source(spec: ManimSceneSpec) -> str:
    payload = json.dumps(
        {
            "background": spec.background,
            "primitives": [
                {
                    "kind": item.kind,
                    "title": item.title,
                    "body": item.body,
                    "source_label": item.source_label,
                    "duration_seconds": item.duration_seconds,
                    "params": item.params,
                }
                for item in spec.primitives
            ],
        },
        ensure_ascii=False,
        sort_keys=True,
    )
    return f'''# Generated by contentmaxxer. Manual edits are safe; `render` preserves bespoke scenes.
import json
import textwrap
from manim import *

config.pixel_width = {spec.width}
config.pixel_height = {spec.height}
config.frame_rate = {spec.fps}
config.frame_width = 9
config.frame_height = 16
SPEC = json.loads({payload!r})
INK = "#F4F7FB"
MUTED = "#A8B3C4"
ACCENT = "#5EEAD4"
PANEL = "#122238"
PANEL_2 = "#0B1829"
WARM = "#FBBF24"
PINK = "#FB7185"


def fitted_text(value, max_width=7.4, size=48, color=INK, weight=NORMAL):
    text = Text(value, font_size=size, color=color, weight=weight, line_spacing=0.9)
    if text.width > max_width:
        text.scale_to_fit_width(max_width)
    return text


def wrapped_text(value, max_width=7.15, max_height=1.3, chars=25, lines=2, size=43, color=INK, weight=BOLD):
    wrapped = textwrap.wrap(value, width=chars, break_long_words=False, break_on_hyphens=False)
    if len(wrapped) > lines:
        wrapped = wrapped[:lines]
        wrapped[-1] = wrapped[-1].rstrip(" .,;:") + "…"
    text = Text("\\n".join(wrapped), font_size=size, color=color, weight=weight, line_spacing=0.78)
    if text.width > max_width:
        text.scale_to_fit_width(max_width)
    if text.height > max_height:
        text.scale_to_fit_height(max_height)
    return text


def source_badge(label):
    badge = RoundedRectangle(corner_radius=0.12, width=3.4, height=0.38, fill_color=PANEL, fill_opacity=0.92, stroke_opacity=0)
    text = fitted_text("SOURCE  " + label, max_width=3.05, size=18, color=MUTED)
    return VGroup(badge, text).move_to(UP * 4.28 + LEFT * 1.9)


def model_cards(item):
    names = ["SOL", "TERRA", "LUNA"]
    cards = VGroup(*[
        VGroup(
            RoundedRectangle(corner_radius=0.18, width=2.25, height=2.55, fill_color=PANEL, fill_opacity=1, stroke_color=ACCENT),
            fitted_text(name, max_width=1.8, size=28, color=ACCENT, weight=BOLD),
        ) for name in names
    ]).arrange(RIGHT, buff=0.28)
    for card in cards:
        card[1].move_to(card[0].get_center())
    return cards


def orbit_trace(item):
    stage = int(item.get("params", {{}}).get("beat_index", 0))
    earth = Circle(radius=1.22, color="#60A5FA", fill_color="#1D4ED8", fill_opacity=0.28)
    atmosphere = Circle(radius=1.38, color="#60A5FA", stroke_opacity=0.22)
    orbit = Ellipse(width=6.15, height=3.45, color=ACCENT, stroke_opacity=0.18 if stage < 2 else 0.72)
    low_path = ArcBetweenPoints(LEFT * 2.7 + UP * 0.15, RIGHT * 2.35 + DOWN * 1.25, angle=-0.5, color=PINK, stroke_opacity=0.48 if stage == 3 else 0.0)
    escape_path = ArcBetweenPoints(LEFT * 2.7 + UP * 0.2, RIGHT * 3.0 + UP * 1.15, angle=0.35, color=WARM, stroke_opacity=0.48 if stage == 3 else 0.0)
    satellite = Dot(orbit.point_from_proportion(0.12), radius=0.11, color=WARM)
    gravity = Arrow(
        satellite.get_center(), earth.get_center(), buff=0.16, color=PINK, stroke_width=5,
        stroke_opacity=1.0,
    )
    velocity = Arrow(
        satellite.get_center(), satellite.get_center() + RIGHT * 1.25 + UP * 0.25,
        buff=0.05, color=WARM, stroke_width=5, stroke_opacity=0.05 if stage < 1 else 1.0,
    )
    gravity_label = fitted_text("gravity pulls inward", size=22, color=PINK).next_to(gravity, LEFT, buff=0.08)
    velocity_label = fitted_text("sideways speed", size=22, color=WARM).next_to(velocity, UP, buff=0.08)
    velocity_label.set_opacity(0.05 if stage < 1 else 1.0)
    stage_labels = ["falling inward", "add sideways speed", "the path keeps curving", "speed changes the path", "falling around Earth"]
    summary = fitted_text(
        stage_labels[min(stage, len(stage_labels) - 1)],
        size=28, color=ACCENT, weight=BOLD,
    ).next_to(earth, DOWN, buff=1.05)
    return VGroup(orbit, low_path, escape_path, atmosphere, earth, satellite, gravity, velocity, gravity_label, velocity_label, summary)


def vector_transform(item):
    origin = Dot(LEFT * 2.3 + DOWN * 0.6, color=INK)
    down = Arrow(origin, origin.get_center() + DOWN * 2.0, buff=0.08, color=PINK, stroke_width=7)
    side = Arrow(origin, origin.get_center() + RIGHT * 2.8, buff=0.08, color=WARM, stroke_width=7)
    curve = ArcBetweenPoints(origin.get_center(), RIGHT * 2.45 + DOWN * 1.65, angle=-0.72, color=ACCENT, stroke_width=7)
    labels = VGroup(
        fitted_text("fall", size=24, color=PINK).next_to(down, LEFT),
        fitted_text("forward", size=24, color=WARM).next_to(side, UP),
        fitted_text("orbit", size=28, color=ACCENT, weight=BOLD).next_to(curve, DOWN),
    )
    return VGroup(origin, down, side, curve, labels)


def gradient_descent(item):
    stage = int(item.get("params", {{}}).get("beat_index", 0))
    axes = Axes(
        x_range=[-3, 3, 1],
        y_range=[0, 5, 1],
        x_length=6.5,
        y_length=4.2,
        axis_config={{"color": MUTED, "stroke_opacity": 0.35, "include_ticks": False}},
    )
    curve = axes.plot(lambda x: 0.42 * x * x + 0.35, x_range=[-2.8, 2.8], color=ACCENT, stroke_width=7)
    point_data = ((-2.45, PINK), (-1.55, WARM), (-0.82, ACCENT), (-0.25, INK))
    points = VGroup()
    for index, (x, color) in enumerate(point_data):
        point = Dot(axes.c2p(x, 0.42 * x * x + 0.35), color=color, radius=0.1)
        point.set_opacity(1.0 if index <= stage else 0.13)
        points.add(point)
    arrows = VGroup()
    for index in range(len(points) - 1):
        arrow = Arrow(points[index], points[index + 1], buff=0.16, color=WARM, stroke_width=4)
        arrow.set_opacity(1.0 if index < stage else 0.12)
        arrows.add(arrow)
    tangent = Arrow(
        axes.c2p(-2.45, 2.87), axes.c2p(-1.15, 1.35), buff=0.05,
        color=PINK, stroke_width=5,
    ).set_opacity(1.0 if stage <= 1 else 0.24)
    stage_labels = ["measure the error", "follow the negative gradient", "recalculate and step", "step size matters", "repeat toward lower loss"]
    summary = fitted_text(
        stage_labels[min(stage, len(stage_labels) - 1)],
        size=27, color=ACCENT, weight=BOLD,
    ).next_to(axes, DOWN, buff=0.35)
    return VGroup(axes, curve, tangent, arrows, points, summary)


def attention_flow(item):
    stage = int(item.get("params", {{}}).get("beat_index", 0))
    tokens = ["the", "bank", "was", "steep"]
    token_boxes = VGroup(*[
        VGroup(
            RoundedRectangle(corner_radius=0.12, width=1.35, height=0.72, fill_color=PANEL, fill_opacity=1, stroke_color=ACCENT),
            fitted_text(token, max_width=1.05, size=24),
        )
        for token in tokens
    ]).arrange(RIGHT, buff=0.22)
    for box in token_boxes:
        box[1].move_to(box[0])
    focus = token_boxes[1]
    arc_strengths = (
        (token_boxes[0], MUTED, 3, 0.25),
        (token_boxes[2], WARM, 5, 0.62),
        (token_boxes[3], PINK, 7, 1.0),
    )
    arcs = VGroup()
    for target, color, width, strength in arc_strengths:
        arc = CurvedArrow(focus.get_top(), target.get_top(), angle=0.62, color=color, stroke_width=width)
        arc.set_opacity(0.12 if stage == 0 else (0.55 if stage == 1 else strength))
        arcs.add(arc)
    second_focus = token_boxes[2]
    parallel_head = VGroup(
        CurvedArrow(second_focus.get_bottom(), token_boxes[0].get_bottom(), angle=-0.62, color=ACCENT, stroke_width=4),
        CurvedArrow(second_focus.get_bottom(), token_boxes[3].get_bottom(), angle=0.62, color=WARM, stroke_width=6),
    )
    parallel_head.set_opacity(0.72 if stage >= 4 else 0.0)
    mixer = VGroup(
        Circle(radius=0.34, fill_color=PANEL, fill_opacity=1, stroke_color=ACCENT),
        fitted_text("Σ", size=27, color=ACCENT, weight=BOLD),
    ).arrange().next_to(token_boxes, RIGHT, buff=0.48)
    mixer[1].move_to(mixer[0])
    mixer.set_opacity(1.0 if stage >= 3 else 0.0)
    focus[0].set_stroke(PINK if stage >= 1 else ACCENT, width=5 if stage >= 1 else 2)
    stage_labels = ["make query, key, value", "compare query with keys", "softmax makes weights", "mix the weighted values", "heads learn different links"]
    label = fitted_text(
        stage_labels[min(stage, len(stage_labels) - 1)],
        size=27, color=ACCENT, weight=BOLD,
    ).next_to(token_boxes, DOWN, buff=0.85)
    return VGroup(token_boxes, arcs, parallel_head, mixer, label)


def timeline(item):
    line = Line(LEFT * 3.2, RIGHT * 3.2, color=ACCENT)
    dots = VGroup(*[Dot(line.point_from_proportion(x), color=ACCENT) for x in (0.0, 0.5, 1.0)])
    return VGroup(line, dots)


def comparison_grid(item):
    return VGroup(*[
        RoundedRectangle(corner_radius=0.12, width=3.25, height=1.15, fill_color=PANEL, fill_opacity=1, stroke_color=ACCENT)
        for _ in range(4)
    ]).arrange_in_grid(rows=2, cols=2, buff=0.25)


def tokens_context(item):
    tokens = VGroup(*[Square(0.32, fill_color=ACCENT, fill_opacity=0.8, stroke_opacity=0) for _ in range(12)])
    return tokens.arrange_in_grid(rows=3, cols=4, buff=0.12)


def eval_bars(item):
    bars = VGroup(*[Rectangle(width=w, height=0.35, fill_color=ACCENT, fill_opacity=0.85, stroke_opacity=0) for w in (2.3, 3.4, 4.8)])
    return bars.arrange(DOWN, aligned_edge=LEFT, buff=0.22)


def agent_loop(item):
    nodes = VGroup(*[Circle(0.43, fill_color=PANEL, fill_opacity=1, stroke_color=ACCENT) for _ in range(4)])
    nodes.arrange_in_grid(rows=2, cols=2, buff=1.0)
    arrows = VGroup(Arrow(nodes[0], nodes[1], buff=0.45), Arrow(nodes[1], nodes[3], buff=0.45), Arrow(nodes[3], nodes[2], buff=0.45), Arrow(nodes[2], nodes[0], buff=0.45))
    return VGroup(nodes, arrows)


def claim_callout(item):
    return RoundedRectangle(corner_radius=0.2, width=7.2, height=2.7, fill_color=PANEL, fill_opacity=1, stroke_color=ACCENT)


def routing_diagram(item):
    center = Circle(0.48, fill_color=ACCENT, fill_opacity=1, stroke_opacity=0)
    targets = VGroup(*[RoundedRectangle(corner_radius=0.1, width=1.6, height=0.7, fill_color=PANEL, fill_opacity=1, stroke_color=ACCENT) for _ in range(3)]).arrange(DOWN, buff=0.35).shift(RIGHT * 2.2)
    arrows = VGroup(*[Arrow(center, target, buff=0.45, stroke_width=3) for target in targets])
    return VGroup(center, targets, arrows)


def before_after(item):
    left = RoundedRectangle(corner_radius=0.16, width=3.1, height=2.1, fill_color=PANEL, fill_opacity=1, stroke_color=MUTED)
    right = RoundedRectangle(corner_radius=0.16, width=3.1, height=2.1, fill_color=PANEL, fill_opacity=1, stroke_color=ACCENT)
    arrow = Arrow(left, right, buff=0.25, color=ACCENT)
    return VGroup(left, arrow, right).arrange(RIGHT, buff=0.25)


PRIMITIVES = {{
    "model_cards": model_cards,
    "timeline": timeline,
    "comparison_grid": comparison_grid,
    "tokens_context": tokens_context,
    "eval_bars": eval_bars,
    "agent_loop": agent_loop,
    "claim_callout": claim_callout,
    "routing_diagram": routing_diagram,
    "before_after": before_after,
    "orbit_trace": orbit_trace,
    "vector_transform": vector_transform,
    "gradient_descent": gradient_descent,
    "attention_flow": attention_flow,
}}


class ContentMaxxerScene(Scene):
    def construct(self):
        self.camera.background_color = SPEC["background"]
        grid = NumberPlane(
            x_range=[-5, 5, 1],
            y_range=[-9, 9, 1],
            background_line_style={{"stroke_color": "#20354D", "stroke_opacity": 0.13, "stroke_width": 1}},
            axis_config={{"stroke_opacity": 0}},
        )
        self.add(grid)
        current_title = None
        current_visual = None
        current_badge = None
        current_caption = None
        caption_panel = RoundedRectangle(
            corner_radius=0.18,
            width=7.45,
            height=1.28,
            fill_color=PANEL_2,
            fill_opacity=0.98,
            stroke_color="#20354D",
            stroke_opacity=0.8,
        ).move_to(DOWN * 4.68)
        self.add(caption_panel)
        for beat_index, item in enumerate(SPEC["primitives"]):
            beat_origin = self.time
            duration = max(0.2, item["duration_seconds"])
            title = wrapped_text(item["title"], size=43, weight=BOLD).move_to(UP * 5.35)
            visual = PRIMITIVES.get(item["kind"], claim_callout)(item).move_to(UP * 0.55)
            badge = source_badge(item["source_label"])
            captions = item.get("params", {{}}).get("captions", [])
            first_caption_text = captions[0]["text"] if captions else item["body"]
            caption = wrapped_text(
                first_caption_text, max_width=6.75, max_height=0.92, chars=25, lines=2, size=35, weight=BOLD,
            ).move_to(caption_panel)
            if current_title is None:
                self.play(
                    FadeIn(title, shift=UP * 0.12),
                    LaggedStart(*[Create(part) for part in visual], lag_ratio=0.08),
                    FadeIn(badge),
                    FadeIn(caption),
                    run_time=min(0.9, duration * 0.2),
                )
            else:
                self.remove(current_title, current_caption)
                self.add(title, caption)
                self.play(
                    ReplacementTransform(current_visual, visual),
                    Transform(current_badge, badge),
                    run_time=min(0.72, duration * 0.16),
                )
            current_title = title
            current_visual = visual
            current_badge = badge if current_badge is None else current_badge
            current_caption = caption
            for caption_index, cue in enumerate(captions[1:], start=1):
                target = beat_origin + cue["start_seconds"]
                if self.time < target:
                    self.wait(target - self.time)
                replacement = wrapped_text(
                    cue["text"], max_width=6.75, max_height=0.92, chars=25, lines=2, size=35, weight=BOLD,
                ).move_to(caption_panel)
                self.remove(current_caption)
                self.add(replacement)
                current_caption = replacement
                animations = []
                if caption_index % 2:
                    animations.append(Indicate(current_visual, color=WARM, scale_factor=1.025))
                if animations:
                    self.play(*animations, run_time=min(0.22, max(0.12, cue["end_seconds"] - cue["start_seconds"])))
            beat_end = beat_origin + duration
            if self.time < beat_end:
                self.wait(beat_end - self.time)
        if current_title is not None:
            self.play(
                FadeOut(VGroup(current_title, current_visual, current_badge, current_caption, caption_panel)),
                run_time=0.35,
            )
'''


HAND_DRAWN_SCENE_LIBRARY = r'''

HAND_FONT = "Chalkboard SE"
MARKER_FONT = "Marker Felt"
CHALK = "#F7F3E8"
TEAL = "#67E8D4"
BLUE = "#74A7FF"
GOLD = "#F9C74F"
CORAL = "#FF718A"
VIOLET = "#C4A7FF"
BOARD = "#081521"
BOARD_EDGE = "#29445C"


def fitted_text(value, max_width=7.4, size=48, color=CHALK, weight=NORMAL, font=HAND_FONT):
    text = Text(value, font=font, font_size=size, color=color, weight=weight, line_spacing=0.88)
    if text.width > max_width:
        text.scale_to_fit_width(max_width)
    return text


def wrapped_text(value, max_width=7.15, max_height=1.3, chars=25, lines=2, size=43, color=CHALK, weight=BOLD, font=HAND_FONT):
    wrapped = textwrap.wrap(value, width=chars, break_long_words=False, break_on_hyphens=False)
    if len(wrapped) > lines:
        wrapped = wrapped[:lines]
        wrapped[-1] = wrapped[-1].rstrip(" .,;:") + "…"
    text = Text("\n".join(wrapped), font=font, font_size=size, color=color, weight=weight, line_spacing=0.72)
    if text.width > max_width:
        text.scale_to_fit_width(max_width)
    if text.height > max_height:
        text.scale_to_fit_height(max_height)
    return text


def _jitter(point, index, seed, amount):
    phase = (index + 1) * (seed + 1.73)
    return np.array(point, dtype=float) + np.array([
        amount * np.sin(phase * 1.91),
        amount * np.cos(phase * 1.37),
        0.0,
    ])


def rough_path(points, color=CHALK, width=4, seed=1, closed=False, fill_color=None, fill_opacity=0.0, passes=3):
    raw = [np.array(point, dtype=float) for point in points]
    strokes = VGroup()
    for pass_index in range(passes):
        amount = 0.012 + pass_index * 0.005
        jittered = [_jitter(point, index, seed + pass_index * 7, amount) for index, point in enumerate(raw)]
        if closed:
            jittered.append(jittered[0])
        path = VMobject()
        if len(raw) <= 4:
            path.set_points_as_corners(jittered)
        else:
            path.set_points_smoothly(jittered)
        opacity = 0.82 if pass_index == 0 else 0.30
        path.set_stroke(color, width=max(1.0, width - pass_index * 0.7), opacity=opacity)
        if pass_index == 0 and fill_opacity:
            path.set_fill(fill_color or color, opacity=fill_opacity)
        strokes.add(path)
    return strokes


def rough_line(start, end, color=CHALK, width=4, seed=1):
    start = np.array(start, dtype=float)
    end = np.array(end, dtype=float)
    points = [interpolate(start, end, alpha) for alpha in (0.0, 0.24, 0.5, 0.76, 1.0)]
    return rough_path(points, color=color, width=width, seed=seed)


def rough_arrow(start, end, color=CHALK, width=5, seed=1):
    start = np.array(start, dtype=float)
    end = np.array(end, dtype=float)
    shaft = rough_line(start, end, color=color, width=width, seed=seed)
    direction = end - start
    angle = np.arctan2(direction[1], direction[0])
    tip = Triangle(fill_color=color, fill_opacity=0.95, stroke_opacity=0).scale(0.13)
    tip.rotate(angle - PI / 2).move_to(end)
    ghost = tip.copy().scale(0.93).shift(LEFT * 0.018 + DOWN * 0.012).set_opacity(0.35)
    return VGroup(shaft, tip, ghost)


def rough_ellipse(width, height, center=ORIGIN, color=CHALK, stroke_width=4, seed=1, fill_color=None, fill_opacity=0.0):
    points = []
    for index in range(49):
        angle = TAU * index / 48
        points.append(np.array([
            center[0] + width * 0.5 * np.cos(angle),
            center[1] + height * 0.5 * np.sin(angle),
            0.0,
        ]))
    return rough_path(
        points,
        color=color,
        width=stroke_width,
        seed=seed,
        closed=True,
        fill_color=fill_color,
        fill_opacity=fill_opacity,
    )


def rough_circle(radius, center=ORIGIN, color=CHALK, stroke_width=4, seed=1, fill_color=None, fill_opacity=0.0):
    return rough_ellipse(
        radius * 2,
        radius * 2,
        center=center,
        color=color,
        stroke_width=stroke_width,
        seed=seed,
        fill_color=fill_color,
        fill_opacity=fill_opacity,
    )


def rough_rect(width, height, center=ORIGIN, color=BOARD_EDGE, stroke_width=3, seed=1, fill_color=None, fill_opacity=0.0):
    x, y = center[0], center[1]
    points = [
        np.array([x - width / 2, y - height / 2, 0.0]),
        np.array([x + width / 2, y - height / 2, 0.0]),
        np.array([x + width / 2, y + height / 2, 0.0]),
        np.array([x - width / 2, y + height / 2, 0.0]),
    ]
    return rough_path(
        points,
        color=color,
        width=stroke_width,
        seed=seed,
        closed=True,
        fill_color=fill_color,
        fill_opacity=fill_opacity,
    )


def hand_label(value, center, color=CHALK, size=24, max_width=2.8, font=HAND_FONT):
    return fitted_text(value, max_width=max_width, size=size, color=color, weight=BOLD, font=font).move_to(center)


def sticky_note(value, center, width=2.65, height=0.78, color=GOLD, seed=1, size=22):
    frame = rough_rect(
        width,
        height,
        center=center,
        color=color,
        stroke_width=3,
        seed=seed,
        fill_color=color,
        fill_opacity=0.08,
    )
    text = wrapped_text(
        value,
        max_width=width - 0.25,
        max_height=height - 0.18,
        chars=20,
        lines=2,
        size=size,
        color=color,
        font=HAND_FONT,
    ).move_to(center)
    tape = rough_line(
        center + LEFT * 0.34 + UP * (height / 2 + 0.04),
        center + RIGHT * 0.34 + UP * (height / 2 + 0.04),
        color=CHALK,
        width=5,
        seed=seed + 31,
    ).set_opacity(0.22)
    return VGroup(frame, text, tape)


def stage_rail(stage):
    dots = VGroup()
    for index in range(5):
        center = np.array([3.48, 2.25 - index * 1.12, 0.0])
        color = GOLD if index == stage else BOARD_EDGE
        dot = rough_circle(
            0.105 if index == stage else 0.075,
            center=center,
            color=color,
            stroke_width=3,
            seed=90 + index,
            fill_color=color,
            fill_opacity=0.78 if index == stage else 0.10,
        )
        dots.add(dot)
    return dots


def visual_board(stage, content, cue_targets=None, highlight_path=None):
    board = rough_rect(
        7.72,
        6.68,
        center=ORIGIN,
        color=BOARD_EDGE,
        stroke_width=2.6,
        seed=300 + stage,
        fill_color=BOARD,
        fill_opacity=0.34,
    )
    corner = hand_label(f"SKETCH {stage + 1}/5", LEFT * 2.92 + UP * 2.92, color=MUTED, size=15, max_width=1.35)
    underline = rough_line(
        LEFT * 3.48 + UP * 2.69,
        LEFT * 2.42 + UP * 2.69,
        color=MUTED,
        width=2,
        seed=330 + stage,
    )
    result = VGroup(board, content, stage_rail(stage), corner, underline)
    result.cue_targets = list(cue_targets or [content])
    result.highlight_path = highlight_path
    return result


def source_badge(label):
    center = UP * 4.28 + LEFT * 2.15
    frame = rough_rect(
        3.0,
        0.42,
        center=center,
        color=BOARD_EDGE,
        stroke_width=2,
        seed=401,
        fill_color=PANEL,
        fill_opacity=0.55,
    )
    text = fitted_text("SOURCE  " + label, max_width=2.68, size=17, color=MUTED, font=HAND_FONT).move_to(center)
    return VGroup(frame, text)


def _mini_earth(center, radius=0.72, seed=1):
    globe = rough_circle(
        radius,
        center=center,
        color=BLUE,
        stroke_width=4,
        seed=seed,
        fill_color="#153B7A",
        fill_opacity=0.42,
    )
    land = rough_path(
        [
            center + LEFT * radius * 0.48 + UP * radius * 0.12,
            center + LEFT * radius * 0.1 + UP * radius * 0.35,
            center + RIGHT * radius * 0.34 + UP * radius * 0.05,
            center + RIGHT * radius * 0.08 + DOWN * radius * 0.25,
            center + LEFT * radius * 0.32 + DOWN * radius * 0.12,
        ],
        color=TEAL,
        width=2.2,
        seed=seed + 12,
    ).set_opacity(0.42)
    return VGroup(globe, land)


def orbit_trace(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    cue_targets = []
    highlight = None

    if stage == 0:
        earth_center = LEFT * 0.65 + DOWN * 0.48
        earth = _mini_earth(earth_center, radius=1.02, seed=10)
        satellite = Dot(RIGHT * 1.35 + UP * 1.25, radius=0.11, color=GOLD)
        gravity = rough_arrow(satellite.get_center(), earth_center + UP * 0.18, color=CORAL, width=5, seed=13)
        trail = VGroup(*[
            Dot(interpolate(satellite.get_center(), earth_center, alpha), radius=0.035, color=CORAL).set_opacity(0.18 + alpha * 0.5)
            for alpha in (0.16, 0.30, 0.44, 0.58)
        ])
        note = sticky_note("gravity keeps pulling", RIGHT * 1.63 + DOWN * 1.63, width=2.55, color=CORAL, seed=15)
        label = hand_label("always falling", LEFT * 2.1 + UP * 1.62, color=CORAL, size=27, max_width=2.2, font=MARKER_FONT)
        content = VGroup(earth, satellite, gravity, trail, note, label)
        cue_targets = [gravity, earth, note, satellite]
        highlight = gravity[0][0]
    elif stage == 1:
        left_center = LEFT * 1.78
        right_center = RIGHT * 1.78
        left_card = rough_rect(3.05, 3.72, center=left_center, color=CORAL, seed=20, fill_color=PANEL, fill_opacity=0.32)
        right_card = rough_rect(3.05, 3.72, center=right_center, color=GOLD, seed=21, fill_color=PANEL, fill_opacity=0.32)
        earth = _mini_earth(left_center + DOWN * 0.52, radius=0.72, seed=22)
        falling_dot = Dot(left_center + UP * 0.82, radius=0.09, color=CORAL)
        fall_arrow = rough_arrow(falling_dot.get_center(), left_center + DOWN * 0.1, color=CORAL, width=4.5, seed=23)
        fall_label = hand_label("1. FALL", left_center + UP * 1.42, color=CORAL, size=27, max_width=2.2, font=MARKER_FONT)
        horizon = rough_path(
            [
                right_center + LEFT * 1.1 + DOWN * 0.62,
                right_center + LEFT * 0.5 + DOWN * 0.78,
                right_center + RIGHT * 0.2 + DOWN * 0.82,
                right_center + RIGHT * 1.1 + DOWN * 0.58,
            ],
            color=BLUE,
            width=3,
            seed=24,
        )
        side_dot = Dot(right_center + LEFT * 0.82 + UP * 0.38, radius=0.09, color=GOLD)
        side_arrow = rough_arrow(side_dot.get_center(), right_center + RIGHT * 0.82 + UP * 0.38, color=GOLD, width=4.5, seed=25)
        side_label = hand_label("2. FORWARD", right_center + UP * 1.42, color=GOLD, size=27, max_width=2.35, font=MARKER_FONT)
        plus = hand_label("+", UP * 0.15, color=CHALK, size=48, max_width=0.5, font=MARKER_FONT)
        content = VGroup(left_card, right_card, earth, falling_dot, fall_arrow, fall_label, horizon, side_dot, side_arrow, side_label, plus)
        cue_targets = [fall_arrow, side_arrow, plus, horizon]
        highlight = side_arrow[0][0]
    elif stage == 2:
        earth_center = DOWN * 0.35
        earth = _mini_earth(earth_center, radius=1.02, seed=30)
        orbit = rough_ellipse(5.8, 3.35, center=earth_center, color=TEAL, stroke_width=4.5, seed=31)
        satellite_point = np.array([2.38, 0.62, 0.0])
        satellite = Dot(satellite_point, radius=0.115, color=GOLD)
        gravity = rough_arrow(satellite_point, earth_center + RIGHT * 0.32, color=CORAL, width=4.5, seed=32)
        velocity = rough_arrow(satellite_point, satellite_point + RIGHT * 1.05 + UP * 0.25, color=GOLD, width=4.5, seed=33)
        equation = sticky_note("fall + forward = curve", UP * 2.05, width=3.85, color=TEAL, seed=34, size=24)
        gravity_label = hand_label("gravity", RIGHT * 0.55 + UP * 0.78, color=CORAL, size=20, max_width=1.2)
        velocity_label = hand_label("speed", RIGHT * 2.73 + UP * 1.23, color=GOLD, size=20, max_width=1.0)
        content = VGroup(orbit, earth, satellite, gravity, velocity, equation, gravity_label, velocity_label)
        cue_targets = [equation, gravity, velocity, orbit]
        highlight = orbit[0]
    elif stage == 3:
        earth_center = DOWN * 0.82
        earth = _mini_earth(earth_center, radius=0.88, seed=40)
        start = LEFT * 3.05 + UP * 1.48
        slow = rough_path(
            [start, LEFT * 1.8 + UP * 0.95, LEFT * 0.65 + UP * 0.1, earth_center + LEFT * 0.28],
            color=CORAL,
            width=4,
            seed=41,
        )
        orbit = rough_ellipse(5.25, 2.75, center=earth_center, color=TEAL, stroke_width=4.5, seed=42)
        fast = rough_path(
            [start + DOWN * 0.24, LEFT * 1.0 + UP * 1.44, RIGHT * 1.0 + UP * 1.62, RIGHT * 3.0 + UP * 1.95],
            color=GOLD,
            width=4,
            seed=43,
        )
        labels = VGroup(
            hand_label("too slow → hits", LEFT * 2.05 + DOWN * 0.1, color=CORAL, size=21, max_width=2.0),
            hand_label("just right → orbit", RIGHT * 1.95 + DOWN * 2.15, color=TEAL, size=21, max_width=2.2),
            hand_label("faster → opens", RIGHT * 2.08 + UP * 2.23, color=GOLD, size=21, max_width=2.0),
        )
        speed_note = sticky_note("speed chooses the path", LEFT * 1.7 + UP * 2.35, width=3.25, color=GOLD, seed=44)
        content = VGroup(earth, slow, orbit, fast, labels, speed_note)
        cue_targets = [slow, orbit, fast, speed_note]
        highlight = orbit[0]
    else:
        earth_center = LEFT * 1.08 + DOWN * 0.28
        earth = _mini_earth(earth_center, radius=1.0, seed=50)
        orbit = rough_ellipse(4.95, 3.05, center=earth_center, color=TEAL, stroke_width=4.5, seed=51)
        satellite = Dot(earth_center + RIGHT * 2.12 + UP * 0.68, radius=0.11, color=GOLD)
        trails = VGroup(*[
            Dot(earth_center + RIGHT * x + UP * y, radius=0.04, color=GOLD).set_opacity(opacity)
            for x, y, opacity in ((1.82, 0.92, 0.25), (1.97, 0.82, 0.45), (2.08, 0.74, 0.7))
        ])
        takeaway = sticky_note(
            "a fall that keeps missing",
            RIGHT * 1.93 + DOWN * 1.65,
            width=3.05,
            height=1.08,
            color=TEAL,
            seed=52,
            size=25,
        )
        no_thruster = VGroup(
            rough_line(RIGHT * 1.35 + UP * 1.85, RIGHT * 2.55 + UP * 1.85, color=MUTED, width=3, seed=53),
            hand_label("no constant thrust", RIGHT * 1.95 + UP * 2.15, color=MUTED, size=20, max_width=2.25),
        )
        content = VGroup(orbit, earth, satellite, trails, takeaway, no_thruster)
        cue_targets = [orbit, satellite, takeaway, no_thruster]
        highlight = orbit[0]
    return visual_board(stage, content, cue_targets=cue_targets, highlight_path=highlight)


def _loss_curve(center=ORIGIN, width=5.6, height=2.8, color=TEAL, seed=60):
    points = []
    for index in range(41):
        x = -1.0 + 2.0 * index / 40
        points.append(center + np.array([x * width / 2, (x * x - 0.6) * height / 2, 0.0]))
    return rough_path(points, color=color, width=4.5, seed=seed)


def _loss_axes(center=ORIGIN, width=6.0, height=3.4, seed=61):
    return VGroup(
        rough_arrow(center + LEFT * width / 2 + DOWN * height * 0.28, center + RIGHT * width / 2 + DOWN * height * 0.28, color=MUTED, width=2.5, seed=seed),
        rough_arrow(center + DOWN * height * 0.42, center + UP * height * 0.55, color=MUTED, width=2.5, seed=seed + 1),
    ).set_opacity(0.55)


def gradient_descent(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    cue_targets = []
    highlight = None
    if stage == 0:
        left = rough_rect(3.15, 3.5, center=LEFT * 1.75, color=CORAL, seed=61, fill_color=PANEL, fill_opacity=0.3)
        right = rough_rect(3.15, 3.5, center=RIGHT * 1.75, color=TEAL, seed=62, fill_color=PANEL, fill_opacity=0.3)
        target = hand_label("target:  10", LEFT * 1.75 + UP * 0.62, color=CHALK, size=27, max_width=2.3)
        prediction = hand_label("model:  17", LEFT * 1.75, color=GOLD, size=27, max_width=2.3)
        gap = rough_arrow(LEFT * 2.48 + DOWN * 0.6, LEFT * 1.03 + DOWN * 0.6, color=CORAL, width=4, seed=63)
        gap_text = hand_label("the gap = loss", LEFT * 1.75 + DOWN * 1.14, color=CORAL, size=23, max_width=2.4, font=MARKER_FONT)
        curve = _loss_curve(RIGHT * 1.75 + DOWN * 0.22, width=2.55, height=1.8, seed=64)
        point = Dot(RIGHT * 0.92 + UP * 0.3, radius=0.1, color=GOLD)
        question = hand_label("how wrong?", RIGHT * 1.75 + UP * 1.25, color=TEAL, size=25, max_width=2.1, font=MARKER_FONT)
        content = VGroup(left, right, target, prediction, gap, gap_text, curve, point, question)
        cue_targets = [target, prediction, gap, curve]
        highlight = curve[0]
    elif stage == 1:
        axes = _loss_axes(DOWN * 0.15, seed=70)
        curve = _loss_curve(DOWN * 0.15, seed=72)
        point = Dot(LEFT * 2.12 + UP * 0.95, radius=0.105, color=GOLD)
        tangent = rough_line(LEFT * 2.78 + UP * 1.68, LEFT * 1.08 + DOWN * 0.02, color=CORAL, width=4, seed=73)
        uphill = rough_arrow(LEFT * 1.9 + UP * 0.75, LEFT * 2.62 + UP * 1.48, color=CORAL, width=4, seed=74)
        downhill = rough_arrow(LEFT * 1.9 + UP * 0.65, LEFT * 1.05 + DOWN * 0.05, color=GOLD, width=4, seed=75)
        notes = VGroup(
            sticky_note("gradient points uphill", RIGHT * 1.86 + UP * 1.85, width=3.1, color=CORAL, seed=76),
            sticky_note("we step the other way", RIGHT * 1.86 + DOWN * 1.63, width=3.1, color=GOLD, seed=77),
        )
        content = VGroup(axes, curve, point, tangent, uphill, downhill, notes)
        cue_targets = [uphill, tangent, downhill, notes]
        highlight = curve[0]
    elif stage == 2:
        axes = _loss_axes(DOWN * 0.15, seed=80)
        curve = _loss_curve(DOWN * 0.15, seed=82)
        positions = [
            LEFT * 2.35 + UP * 1.18,
            LEFT * 1.42 + UP * 0.10,
            LEFT * 0.68 + DOWN * 0.42,
            LEFT * 0.05 + DOWN * 0.64,
        ]
        dots = VGroup()
        steps = VGroup()
        numbers = VGroup()
        for index, position in enumerate(positions):
            dot = Dot(position, radius=0.10, color=(CORAL, GOLD, TEAL, CHALK)[index])
            dots.add(dot)
            numbers.add(hand_label(str(index + 1), position + UP * 0.34, color=(CORAL, GOLD, TEAL, CHALK)[index], size=18, max_width=0.3))
            if index < len(positions) - 1:
                steps.add(rough_arrow(position, positions[index + 1], color=GOLD, width=3.5, seed=83 + index))
        loop_note = sticky_note("measure → step → measure", RIGHT * 1.85 + UP * 1.62, width=3.35, color=TEAL, seed=88)
        recalc = hand_label("recalculate here", RIGHT * 1.88 + DOWN * 1.45, color=MUTED, size=22, max_width=2.5)
        content = VGroup(axes, curve, steps, dots, numbers, loop_note, recalc)
        cue_targets = [dots[0], steps[0], dots[2], loop_note]
        highlight = curve[0]
    elif stage == 3:
        cards = VGroup()
        labels = (("tiny", CORAL), ("useful", TEAL), ("too big", GOLD))
        for index, (label, color) in enumerate(labels):
            center = LEFT * 2.35 + RIGHT * index * 2.35
            frame = rough_rect(2.08, 3.72, center=center, color=color, seed=90 + index, fill_color=PANEL, fill_opacity=0.30)
            curve = _loss_curve(center + DOWN * 0.25, width=1.65, height=1.35, color=color, seed=94 + index)
            title = hand_label(label, center + UP * 1.42, color=color, size=25, max_width=1.6, font=MARKER_FONT)
            if index == 0:
                step = rough_arrow(center + LEFT * 0.63 + UP * 0.32, center + LEFT * 0.31 + DOWN * 0.06, color=color, width=3, seed=98)
            elif index == 1:
                step = rough_arrow(center + LEFT * 0.62 + UP * 0.32, center + RIGHT * 0.08 + DOWN * 0.52, color=color, width=3, seed=99)
            else:
                step = rough_arrow(center + LEFT * 0.62 + UP * 0.32, center + RIGHT * 0.75 + UP * 0.22, color=color, width=3, seed=100)
            cards.add(VGroup(frame, curve, title, step))
        note = sticky_note("learning rate = step size", DOWN * 2.45, width=3.45, color=GOLD, seed=101)
        content = VGroup(cards, note)
        cue_targets = [cards[0], cards[1], cards[2], note]
        highlight = cards[1][1][0]
    else:
        axes = _loss_axes(LEFT * 0.55 + DOWN * 0.15, width=5.1, seed=110)
        curve = _loss_curve(LEFT * 0.55 + DOWN * 0.15, width=4.75, seed=112)
        positions = [
            LEFT * 2.45 + UP * 1.04,
            LEFT * 1.55 + UP * 0.02,
            LEFT * 0.78 + DOWN * 0.48,
            LEFT * 0.12 + DOWN * 0.68,
        ]
        dots = VGroup(*[Dot(position, radius=0.095, color=color) for position, color in zip(positions, (CORAL, GOLD, TEAL, CHALK))])
        steps = VGroup(*[
            rough_arrow(positions[index], positions[index + 1], color=GOLD, width=3.2, seed=114 + index)
            for index in range(len(positions) - 1)
        ])
        cycle = sticky_note("repeat until the loss stops improving", RIGHT * 2.12 + UP * 1.25, width=3.0, height=1.28, color=TEAL, seed=118, size=22)
        boundary = sticky_note("not every surface has one perfect bottom", RIGHT * 2.12 + DOWN * 1.48, width=3.0, height=1.28, color=VIOLET, seed=119, size=21)
        content = VGroup(axes, curve, steps, dots, cycle, boundary)
        cue_targets = [steps, dots[-1], cycle, boundary]
        highlight = curve[0]
    return visual_board(stage, content, cue_targets=cue_targets, highlight_path=highlight)


def _token_card(value, center, color=TEAL, width=1.25, seed=1, size=22):
    frame = rough_rect(width, 0.68, center=center, color=color, stroke_width=3, seed=seed, fill_color=PANEL, fill_opacity=0.48)
    text = fitted_text(value, max_width=width - 0.18, size=size, color=CHALK, font=HAND_FONT).move_to(center)
    return VGroup(frame, text)


def attention_flow(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    cue_targets = []
    highlight = None
    if stage == 0:
        token = _token_card("bank", UP * 1.75, color=GOLD, width=1.6, seed=120, size=27)
        labels = (("Q", CORAL, LEFT * 2.15), ("K", TEAL, ORIGIN), ("V", VIOLET, RIGHT * 2.15))
        projections = VGroup()
        arrows = VGroup()
        for index, (label, color, x_shift) in enumerate(labels):
            center = x_shift + DOWN * 0.65
            card = _token_card(label, center, color=color, width=1.15, seed=121 + index, size=30)
            detail = hand_label(
                ("asks", "matches", "carries")[index],
                center + DOWN * 0.78,
                color=color,
                size=20,
                max_width=1.3,
                font=MARKER_FONT,
            )
            arrow = rough_arrow(token.get_bottom(), center + UP * 0.36, color=color, width=3.5, seed=125 + index)
            projections.add(VGroup(card, detail))
            arrows.add(arrow)
        note = sticky_note("one token → three roles", DOWN * 2.34, width=3.4, color=GOLD, seed=129)
        content = VGroup(token, arrows, projections, note)
        cue_targets = [token, projections[0], projections[1], projections[2], note]
        highlight = arrows[1][0][0]
    elif stage == 1:
        query = _token_card("QUERY\nbank", LEFT * 2.42 + UP * 0.52, color=CORAL, width=1.75, seed=130, size=20)
        key_values = (("the", "0.1", MUTED), ("was", "0.6", GOLD), ("steep", "0.9", CORAL))
        keys = VGroup()
        arrows = VGroup()
        for index, (word, score, color) in enumerate(key_values):
            center = RIGHT * 1.65 + UP * (1.45 - index * 1.4)
            card = _token_card(word, center, color=color, width=1.55, seed=131 + index)
            score_text = hand_label(score, center + RIGHT * 1.05, color=color, size=24, max_width=0.7, font=MARKER_FONT)
            arrow = rough_arrow(query.get_right(), center + LEFT * 0.82, color=color, width=2.5 + index, seed=135 + index)
            keys.add(VGroup(card, score_text))
            arrows.add(arrow)
        note = sticky_note("compare Q with every K", LEFT * 1.48 + DOWN * 1.72, width=3.15, color=CORAL, seed=139)
        content = VGroup(query, arrows, keys, note)
        cue_targets = [query, keys[0], keys[1], keys[2], note]
        highlight = arrows[-1][0][0]
    elif stage == 2:
        scores = VGroup(
            hand_label("0.1", LEFT * 2.72 + UP * 1.28, color=MUTED, size=25, max_width=0.7),
            hand_label("0.6", LEFT * 2.72, color=GOLD, size=25, max_width=0.7),
            hand_label("0.9", LEFT * 2.72 + DOWN * 1.28, color=CORAL, size=25, max_width=0.7),
        )
        funnel = rough_path(
            [
                LEFT * 1.95 + UP * 1.7,
                LEFT * 0.75 + UP * 0.55,
                LEFT * 0.75 + DOWN * 0.55,
                LEFT * 1.95 + DOWN * 1.7,
            ],
            color=TEAL,
            width=4,
            seed=140,
        )
        softmax = hand_label("softmax", LEFT * 1.32, color=TEAL, size=22, max_width=1.35, font=MARKER_FONT)
        bar_specs = (("10%", 0.65, MUTED), ("35%", 1.45, GOLD), ("55%", 2.25, CORAL))
        bars = VGroup()
        for index, (label, width, color) in enumerate(bar_specs):
            y = 1.3 - index * 1.3
            stroke = rough_line(RIGHT * 0.35 + UP * y, RIGHT * (0.35 + width) + UP * y, color=color, width=12, seed=143 + index)
            text = hand_label(label, RIGHT * 3.05 + UP * y, color=color, size=22, max_width=0.75)
            bars.add(VGroup(stroke, text))
        note = sticky_note("scores become weights", DOWN * 2.33, width=3.3, color=TEAL, seed=147)
        content = VGroup(scores, funnel, softmax, bars, note)
        cue_targets = [scores, funnel, bars[0], bars[2], note]
        highlight = bars[2][0][0]
    elif stage == 3:
        values = VGroup(
            _token_card("V₁", LEFT * 2.7 + UP * 1.35, color=MUTED, width=1.1, seed=150, size=25),
            _token_card("V₂", LEFT * 2.7, color=GOLD, width=1.1, seed=151, size=25),
            _token_card("V₃", LEFT * 2.7 + DOWN * 1.35, color=CORAL, width=1.1, seed=152, size=25),
        )
        arrows = VGroup()
        for index, value in enumerate(values):
            arrows.add(rough_arrow(value.get_right(), LEFT * 0.18 + UP * (0.28 - index * 0.28), color=(MUTED, GOLD, CORAL)[index], width=3 + index, seed=154 + index))
        mixer = rough_circle(0.62, center=RIGHT * 0.38, color=TEAL, stroke_width=4, seed=158, fill_color=TEAL, fill_opacity=0.08)
        sigma = hand_label("Σ", RIGHT * 0.38, color=TEAL, size=38, max_width=0.65, font=MARKER_FONT)
        output = _token_card("bank\n+ context", RIGHT * 2.5, color=TEAL, width=1.9, seed=159, size=21)
        output_arrow = rough_arrow(RIGHT * 1.02, output.get_left(), color=TEAL, width=4, seed=160)
        note = sticky_note("weighted values mix", DOWN * 2.32, width=3.2, color=TEAL, seed=161)
        content = VGroup(values, arrows, mixer, sigma, output_arrow, output, note)
        cue_targets = [values, arrows, mixer, output, note]
        highlight = output_arrow[0][0]
    else:
        panels = VGroup()
        colors = (CORAL, GOLD, TEAL)
        link_pairs = ((0, 2), (1, 3), (0, 3))
        for index in range(3):
            center = LEFT * 2.38 + RIGHT * index * 2.38
            frame = rough_rect(2.08, 3.75, center=center, color=colors[index], seed=170 + index, fill_color=PANEL, fill_opacity=0.30)
            title = hand_label(f"HEAD {index + 1}", center + UP * 1.45, color=colors[index], size=21, max_width=1.5, font=MARKER_FONT)
            token_dots = VGroup(*[
                rough_circle(
                    0.16,
                    center=center + LEFT * 0.66 + RIGHT * dot_index * 0.44 + DOWN * 0.12,
                    color=CHALK,
                    stroke_width=2,
                    seed=174 + index * 4 + dot_index,
                    fill_color=CHALK,
                    fill_opacity=0.16,
                )
                for dot_index in range(4)
            ])
            start_index, end_index = link_pairs[index]
            link = rough_arrow(
                token_dots[start_index].get_center() + UP * 0.08,
                token_dots[end_index].get_center() + UP * 0.08,
                color=colors[index],
                width=3,
                seed=190 + index,
            )
            meaning = hand_label(
                ("syntax", "position", "meaning")[index],
                center + DOWN * 1.12,
                color=colors[index],
                size=20,
                max_width=1.55,
            )
            panels.add(VGroup(frame, title, token_dots, link, meaning))
        combine = sticky_note("different links → richer context", DOWN * 2.45, width=3.75, color=VIOLET, seed=195)
        content = VGroup(panels, combine)
        cue_targets = [panels[0], panels[1], panels[2], combine]
        highlight = panels[2][3][0][0]
    return visual_board(stage, content, cue_targets=cue_targets, highlight_path=highlight)


def vector_transform(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    origin = Dot(LEFT * 1.8 + DOWN * 0.2, color=CHALK)
    down = rough_arrow(origin.get_center(), origin.get_center() + DOWN * 1.8, color=CORAL, seed=210)
    side = rough_arrow(origin.get_center(), origin.get_center() + RIGHT * 2.7, color=GOLD, seed=211)
    curve = rough_path(
        [origin.get_center(), LEFT * 0.8 + DOWN * 0.7, RIGHT * 0.5 + DOWN * 1.25, RIGHT * 2.25 + DOWN * 1.45],
        color=TEAL,
        width=5,
        seed=212,
    )
    content = VGroup(origin, down, side, curve, sticky_note("vectors combine", UP * 1.8, color=TEAL, seed=213))
    return visual_board(stage, content, cue_targets=[down, side, curve], highlight_path=curve[0])


def model_cards(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    cards = VGroup()
    for index, (name, color) in enumerate((("SOL", CORAL), ("TERRA", GOLD), ("LUNA", TEAL))):
        center = LEFT * 2.3 + RIGHT * index * 2.3
        cards.add(VGroup(
            rough_rect(1.95, 3.2, center=center, color=color, seed=220 + index, fill_color=PANEL, fill_opacity=0.32),
            hand_label(name, center, color=color, size=28, max_width=1.5, font=MARKER_FONT),
        ))
    return visual_board(stage, cards, cue_targets=list(cards))


def timeline(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    line = rough_line(LEFT * 3.0, RIGHT * 3.0, color=TEAL, width=4, seed=230)
    dots = VGroup(*[rough_circle(0.13, center=LEFT * 3.0 + RIGHT * index * 1.5, color=GOLD, seed=231 + index, fill_color=GOLD, fill_opacity=0.55) for index in range(5)])
    content = VGroup(line, dots)
    return visual_board(stage, content, cue_targets=list(dots), highlight_path=line[0])


def comparison_grid(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    cards = VGroup(*[
        rough_rect(2.75, 1.55, center=LEFT * 1.5 + RIGHT * (index % 2) * 3.0 + UP * 1.0 + DOWN * (index // 2) * 2.0, color=(CORAL, GOLD, TEAL, VIOLET)[index], seed=240 + index, fill_color=PANEL, fill_opacity=0.3)
        for index in range(4)
    ])
    return visual_board(stage, cards, cue_targets=list(cards))


def tokens_context(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    tokens = VGroup(*[
        _token_card(str(index + 1), LEFT * 2.25 + RIGHT * (index % 4) * 1.5 + UP * 1.0 + DOWN * (index // 4) * 1.05, color=(TEAL, GOLD, CORAL)[index % 3], width=1.1, seed=250 + index)
        for index in range(12)
    ])
    return visual_board(stage, tokens, cue_targets=list(tokens))


def eval_bars(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    bars = VGroup(*[
        rough_line(LEFT * 2.65 + UP * (1.25 - index * 1.15), LEFT * 2.65 + RIGHT * width + UP * (1.25 - index * 1.15), color=(CORAL, GOLD, TEAL)[index], width=12, seed=270 + index)
        for index, width in enumerate((2.1, 3.4, 4.8))
    ])
    return visual_board(stage, bars, cue_targets=list(bars), highlight_path=bars[-1][0])


def agent_loop(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    nodes = VGroup(*[
        rough_circle(0.48, center=LEFT * 1.3 + RIGHT * (index % 2) * 2.6 + UP * 1.15 + DOWN * (index // 2) * 2.3, color=(CORAL, GOLD, TEAL, VIOLET)[index], seed=280 + index, fill_color=PANEL, fill_opacity=0.5)
        for index in range(4)
    ])
    links = VGroup(
        rough_arrow(nodes[0].get_center(), nodes[1].get_center(), color=GOLD, seed=285),
        rough_arrow(nodes[1].get_center(), nodes[3].get_center(), color=TEAL, seed=286),
        rough_arrow(nodes[3].get_center(), nodes[2].get_center(), color=VIOLET, seed=287),
        rough_arrow(nodes[2].get_center(), nodes[0].get_center(), color=CORAL, seed=288),
    )
    content = VGroup(nodes, links)
    return visual_board(stage, content, cue_targets=list(nodes), highlight_path=links[0][0][0])


def claim_callout(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    note = sticky_note(item.get("body", "source-backed claim"), ORIGIN, width=5.8, height=2.1, color=TEAL, seed=290, size=29)
    return visual_board(stage, note, cue_targets=[note])


def routing_diagram(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    center = rough_circle(0.48, center=LEFT * 1.65, color=GOLD, seed=300, fill_color=GOLD, fill_opacity=0.18)
    targets = VGroup(*[
        rough_rect(1.65, 0.75, center=RIGHT * 1.65 + UP * (1.1 - index * 1.1), color=(CORAL, TEAL, VIOLET)[index], seed=301 + index, fill_color=PANEL, fill_opacity=0.4)
        for index in range(3)
    ])
    arrows = VGroup(*[rough_arrow(center.get_center(), target.get_center(), color=TEAL, width=3, seed=305 + index) for index, target in enumerate(targets)])
    content = VGroup(center, arrows, targets)
    return visual_board(stage, content, cue_targets=list(targets), highlight_path=arrows[1][0][0])


def before_after(item):
    stage = int(item.get("params", {}).get("beat_index", 0))
    left = rough_rect(2.65, 2.5, center=LEFT * 1.75, color=MUTED, seed=310, fill_color=PANEL, fill_opacity=0.35)
    right = rough_rect(2.65, 2.5, center=RIGHT * 1.75, color=TEAL, seed=311, fill_color=PANEL, fill_opacity=0.35)
    arrow = rough_arrow(LEFT * 0.3, RIGHT * 0.3, color=GOLD, width=4, seed=312)
    content = VGroup(left, arrow, right)
    return visual_board(stage, content, cue_targets=[left, arrow, right], highlight_path=arrow[0][0])


PRIMITIVES = {
    "model_cards": model_cards,
    "timeline": timeline,
    "comparison_grid": comparison_grid,
    "tokens_context": tokens_context,
    "eval_bars": eval_bars,
    "agent_loop": agent_loop,
    "claim_callout": claim_callout,
    "routing_diagram": routing_diagram,
    "before_after": before_after,
    "orbit_trace": orbit_trace,
    "vector_transform": vector_transform,
    "gradient_descent": gradient_descent,
    "attention_flow": attention_flow,
}


def chalk_dust():
    dust = VGroup()
    for index in range(96):
        x = -4.35 + ((index * 1.731) % 8.7)
        y = -7.85 + ((index * 2.417) % 15.7)
        radius = 0.006 + (index % 3) * 0.003
        dust.add(Dot(np.array([x, y, 0.0]), radius=radius, color=CHALK).set_opacity(0.025 + (index % 5) * 0.008))
    return dust


def cue_animation(scene, visual, cue_index, run_time):
    animations = []
    targets = getattr(visual, "cue_targets", [])
    if targets:
        target = targets[cue_index % len(targets)]
        animations.append(Circumscribe(target, color=(GOLD, TEAL, CORAL)[cue_index % 3], fade_out=True, time_width=0.45))
    highlight = getattr(visual, "highlight_path", None)
    if highlight is not None and cue_index % 2:
        flash = highlight.copy().set_stroke((GOLD, TEAL, CORAL)[cue_index % 3], width=10, opacity=0.92)
        animations.append(ShowPassingFlash(flash, time_width=0.32))
    if not animations:
        animations.append(Indicate(visual, color=GOLD, scale_factor=1.015))
    scene.play(AnimationGroup(*animations, lag_ratio=0.05), run_time=run_time)


class ContentMaxxerScene(Scene):
    def construct(self):
        self.camera.background_color = SPEC["background"]
        self.add(chalk_dust())
        current_title = None
        current_visual = None
        current_badge = None
        current_caption = None

        caption_center = DOWN * 4.68
        caption_panel = rough_rect(
            7.48,
            1.28,
            center=caption_center,
            color=BOARD_EDGE,
            stroke_width=2.6,
            seed=500,
            fill_color=PANEL_2,
            fill_opacity=0.92,
        )
        self.add(caption_panel)

        for beat_index, item in enumerate(SPEC["primitives"]):
            beat_origin = self.time
            duration = max(0.2, item["duration_seconds"])
            title_text = wrapped_text(
                item["title"],
                size=45,
                weight=BOLD,
                font=MARKER_FONT,
            ).move_to(UP * 5.35)
            title_underline = rough_line(
                title_text.get_corner(DL) + DOWN * 0.10,
                title_text.get_corner(DR) + DOWN * 0.10,
                color=GOLD,
                width=3.2,
                seed=510 + beat_index,
            )
            title = VGroup(title_text, title_underline)
            visual = PRIMITIVES.get(item["kind"], claim_callout)(item).move_to(UP * 0.42)
            badge = source_badge(item["source_label"])
            captions = item.get("params", {}).get("captions", [])
            first_caption_text = captions[0]["text"] if captions else item["body"]
            caption = wrapped_text(
                first_caption_text,
                max_width=6.75,
                max_height=0.92,
                chars=25,
                lines=2,
                size=34,
                weight=BOLD,
                font=HAND_FONT,
            ).move_to(caption_center)

            if current_title is None:
                self.play(
                    FadeIn(title, shift=UP * 0.10),
                    FadeIn(badge),
                    FadeIn(caption),
                    run_time=min(0.42, duration * 0.09),
                )
                self.play(
                    FadeIn(visual[0]),
                    LaggedStart(*[Create(part) for part in visual[1:]], lag_ratio=0.10),
                    run_time=min(1.0, duration * 0.19),
                )
            else:
                self.remove(current_caption)
                self.add(caption)
                self.play(
                    FadeOut(current_title, shift=UP * 0.08),
                    FadeOut(current_visual, shift=LEFT * 0.10),
                    FadeOut(current_badge),
                    run_time=min(0.24, duration * 0.04),
                )
                self.play(
                    FadeIn(title, shift=UP * 0.08),
                    FadeIn(badge),
                    FadeIn(visual[0]),
                    LaggedStart(
                        *[FadeIn(part, shift=UP * 0.05) for part in visual[1:]],
                        lag_ratio=0.07,
                    ),
                    run_time=min(0.72, duration * 0.13),
                )

            current_title = title
            current_visual = visual
            current_badge = badge
            current_caption = caption

            for caption_index, cue in enumerate(captions[1:], start=1):
                target_time = beat_origin + cue["start_seconds"]
                if self.time < target_time:
                    self.wait(target_time - self.time)
                replacement = wrapped_text(
                    cue["text"],
                    max_width=6.75,
                    max_height=0.92,
                    chars=25,
                    lines=2,
                    size=34,
                    weight=BOLD,
                    font=HAND_FONT,
                ).move_to(caption_center)
                self.remove(current_caption)
                self.add(replacement)
                current_caption = replacement
                cue_animation(
                    self,
                    current_visual,
                    caption_index,
                    min(0.26, max(0.14, cue["end_seconds"] - cue["start_seconds"])),
                )

            beat_end = beat_origin + duration
            if self.time < beat_end:
                self.wait(beat_end - self.time)

        if current_title is not None:
            self.play(
                FadeOut(VGroup(current_title, current_visual, current_badge, current_caption, caption_panel)),
                run_time=0.42,
            )
'''


def _scene_source(spec: ManimSceneSpec) -> str:
    payload = json.dumps(
        {
            "background": spec.background,
            "primitives": [
                {
                    "kind": item.kind,
                    "title": item.title,
                    "body": item.body,
                    "source_label": item.source_label,
                    "duration_seconds": item.duration_seconds,
                    "params": item.params,
                }
                for item in spec.primitives
            ],
        },
        ensure_ascii=False,
        sort_keys=True,
    )
    header = f'''# Generated by contentmaxxer hand-drawn animation director.
import json
import textwrap
import numpy as np
from manim import *

config.pixel_width = {spec.width}
config.pixel_height = {spec.height}
config.frame_rate = {spec.fps}
config.frame_width = 9
config.frame_height = 16
SPEC = json.loads({payload!r})
INK = "#F4F7FB"
MUTED = "#A8B3C4"
ACCENT = "#5EEAD4"
PANEL = "#122238"
PANEL_2 = "#0B1829"
WARM = "#FBBF24"
PINK = "#FB7185"

'''
    return header + HAND_DRAWN_SCENE_LIBRARY


def write_scene_py(job_dir: Path, spec: ManimSceneSpec) -> Path:
    path = job_dir / "video" / "manim" / "scene.py"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_scene_source(spec), encoding="utf-8")
    return path


def manim_available() -> bool:
    return importlib.util.find_spec("manim") is not None or shutil.which("manim") is not None


def render_manim(scene_path: Path, output_path: Path) -> Tuple[Path, str]:
    if not manim_available():
        raise RuntimeError("Manim is not installed. Install Manim or use --renderer auto|raster.")
    media_dir = output_path.parent / "manim_media"
    command = [sys.executable, "-m", "manim", str(scene_path), "ContentMaxxerScene", "-qh", "--media_dir", str(media_dir)]
    completed = subprocess.run(command, text=True, capture_output=True)
    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout)[-2000:]
        raise RuntimeError(f"Manim render failed: {detail}")
    candidates = sorted(media_dir.rglob("ContentMaxxerScene.mp4"), key=lambda path: path.stat().st_mtime)
    if not candidates:
        raise RuntimeError("Manim completed but did not produce ContentMaxxerScene.mp4")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(candidates[-1], output_path)
    return output_path, " ".join(command)
